# Generated by Django 4.1.2 on 2022-10-18 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiposListas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_lista_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Lista',
                'verbose_name_plural': 'Tipos de Listas',
                'db_table': 'tipo_lista',
            },
        ),
        migrations.CreateModel(
            name='ElementosListas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('elemento_lista_id', models.CharField(max_length=255)),
                ('tipo_lista_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.tiposlistas')),
            ],
            options={
                'verbose_name': 'Elemento de Lista',
                'verbose_name_plural': 'Elementos de Listas',
                'db_table': 'elemento_lista',
            },
        ),
    ]
