# Generated by Django 4.1.2 on 2022-10-18 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=15)),
                ('nombre1', models.CharField(max_length=100)),
                ('nombre2', models.CharField(max_length=100)),
                ('apellido1', models.CharField(max_length=100)),
                ('appellido2', models.CharField(max_length=100)),
                ('ciudad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_tercero', to='terceros.elementoslistas')),
                ('departamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamento_tercero', to='terceros.elementoslistas')),
                ('tipo_contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_contribuyente_tercero', to='terceros.elementoslistas')),
                ('tipo_identificacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_identificacion_tercero', to='terceros.elementoslistas')),
                ('tipo_tercero_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_tercero_tercero', to='terceros.elementoslistas')),
            ],
            options={
                'verbose_name': 'Tercero',
                'verbose_name_plural': 'Terceros',
                'db_table': 'tercero',
            },
        ),
    ]
