# Generated by Django 4.1.2 on 2022-10-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0002_tercero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewTercero',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('departamento', models.CharField(db_column='departamento', max_length=255)),
                ('municipio', models.CharField(db_column='municipío', max_length=255)),
                ('tipo_identifacion', models.CharField(db_column='tipo_identificacion', max_length=255)),
                ('identificacion', models.CharField(db_column='identifacion', max_length=255)),
                ('nombres', models.CharField(db_column='nombres', max_length=255)),
                ('tipo_tercero', models.CharField(db_column='tipo_tercero', max_length=255)),
            ],
            options={
                'verbose_name': 'Vista Tercero',
                'verbose_name_plural': 'Vistas Terceros',
                'db_table': 'vw_tercero',
                'managed': False,
            },
        ),
    ]
