# Generated by Django 4.1.2 on 2022-10-19 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0003_viewtercero'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='viewtercero',
            table='vwterceros',
        ),
    ]
